#include "../incs/libftprintf.h"
#include <stdio.h>
int main(void){
    int p = 10;
    printf("printf 100 :    %s\n", "100");
    ft_printf("ft_printf 100 : %s\n", "100");
    printf("printf 100 :    %#x\n", 100);
    ft_printf("ft_printf 100 : %#x\n", 100);
    printf("printf 10 :    %d\n", 10);
    ft_printf("ft_printf 10 : %d\n", 10);
    printf("printf +010c :    %+010c\n", 'c');
    ft_printf("ft_printf +010c : %+010c\n", 'c');
    printf("printf 0#10c :    %0#10c\n", 'c');
    ft_printf("ft_printf 0#10c : %0#10c\n", 'c');
    printf("printf 0 10c :    %0 10c\n", 'c');
    ft_printf("ft_printf 0 10c : %0 10c\n", 'c');
    printf("printf +-10c :    %+-10c\n", 'c');
    ft_printf("ft_printf +-10c : %+-10c\n", 'c');
    printf("printf +#10c :    %+#10c\n", 'c');
    ft_printf("ft_printf +#10c : %+#10c\n", 'c');
    printf("printf -#10c :    %-#10c\n", 'c');
    ft_printf("ft_printf -#10c : %-#10c\n", 'c');
    printf("printf - 10c :    %- 10c\n", 'c');
    ft_printf("ft_printf - 10c : %- 10c\n", 'c');
    printf("printf # 10c :    %# 10c\n", 'c');
    ft_printf("ft_printf # 10c : %# 10c\n", 'c');
    printf("printf +010s :    %+010s\n", "home, sweet home1");
    ft_printf("ft_printf +010s : %+010s\n", "home, sweet home1");
    printf("printf 0#10s :    %0#10s\n", "home, sweet home2");
    ft_printf("ft_printf 0#10s : %0#10s\n", "home, sweet home2");
    printf("printf 0 10s :    %0 10s\n", "home, sweet home3");
    ft_printf("ft_printf 0 10s : %0 10s\n", "home, sweet home3");
    printf("printf +-10s :    %+-10s\n", "home, sweet home4");
    ft_printf("ft_printf +-10s : %+-10s\n", "home, sweet home4");
    printf("printf +#10s :    %+#10s\n", "home, sweet home5");
    ft_printf("ft_printf +#10s : %+#10s\n", "home, sweet home5");
    printf("printf -#10s :    %-#10s\n", "home, sweet home6");
    ft_printf("ft_printf -#10s : %-#10s\n", "home, sweet home6");
    printf("printf - 10s :    %- 10s\n", "home, sweet home7");
    ft_printf("ft_printf - 10s : %- 10s\n", "home, sweet home7");
    printf("printf # 10s :    %# 10s\n", "home, sweet home8");
    ft_printf("ft_printf # 10s : %# 10s\n\n\n", "home, sweet home8");
    ft_printf("ft_printf i : %.10i d : %.10d\n", 1234567, 1234567);
    printf("printf    i : %.10i d : %.10d\n", 1234567, 1234567);
    ft_printf("ft_printf u : %u\n", 2147483);
    printf("printf    u : %u\n", 2147483);
    ft_printf("ft_printf c : %c\n", '%');
    printf("printf    c : %c\n", '%');
    ft_printf("ft_printf p : %p\n", &p);
    printf("printf    p : %p\n", &p);
    ft_printf("ft_printf x: %x\n", 200);
    printf("printf    x: %x\n", 200);
    ft_printf("ft_printf s: %.s\n", "home, sweet home");
    printf("printf    s: %.s\n", "home, sweet home");
    ft_printf("ft_printf s : %s c : %c\n", "1234567", '!');
    printf("printf    s : %s c : %c\n", "1234567", '!');
    ft_printf("ft_printf %% %c\n", '%');
    printf("printf %% %c\n", '%');
}
